FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY cmd/ ./cmd/
COPY internal/ ./internal/
RUN go build -o client ./cmd/client

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache netcat-openbsd
COPY --from=builder /app/client .
COPY start.sh .
RUN chmod +x start.sh

ENTRYPOINT ["./start.sh"]